module.exports = {
  users: [
    {
      username: 'alabert',
      password: 'password',
      firstname: 'burton',
      lastname: 'guster',
      email: 'gus@psych.net',
      phonenumber: '555555555',
      zipcode: '93101',
    },
    {
      username: 'cat catsby',
      password: 'password',
      firstname: 'sydney',
      lastname: 'kitteh',
      email: 'grump@grump.net',
      phonenumber: '555555555',
      zipcode: '60615',
      isAdmin: true,
    },
  ],
  userpayments: [
    {
      userId: 1,
      cardname: 'visa debit card',
      nameoncard: 'Burton Guster',
      billingaddress: '123 Fake Street, Santa Barbara, California',
      ccnumber: 1234567891024,
      ccsecuritycode: 123,
      ccexpiration: '2/25',
      zipcode: '93101',
    },
    {
      userId: 1,
      cardname: 'home depot credit card',
      nameoncard: 'Burton Guster',
      billingaddress: '123 Fake Street, Santa Barbara, California',
      ccnumber: 564654156156,
      ccsecuritycode: 654,
      ccexpiration: '1/24',
      zipcode: '93101',
    },
  ],
  useraddresses: [
    {
      userId: 1,
      street: '123 Fake Street, Santa Barbara, California',
      city: 'Santa Barbara',
      state: 'California',
      zipcode: '93101',
    },
  ],
  items: [
    {
      id: 1,
      title: 'Babe Ruths Jersey',
      description: 'Game worn jersey from 1928-1930 !!!',
      price: 599,
      inventoryquantity: 5,
    },
    {
      id: 2,
      title: 'Air Jordan 5 Off-White',
      description: '2020 Chicago All Star Jordan 5 Special Release !!',
      price: 110000,
      inventoryquantity: 2,
    },
    {
      title: 'Air Jordan 6 Off-White',
      description: '2021 Chicago All Star Jordan 6 Special Release !!',
      price: 110000,
      inventoryquantity: 2,
    },
  ],
  imagesOfItems: [
    {
      itemId: 1,
      url: 'Game worn jersey from 1928-1930 !!!',
      description: 'Babe Ruth ate so many hot dogs in this bad boy!',
      alttext: 'Babe Ruth = Hot Dogs',
    },
    {
      itemId: 2,
      url: '2020 Chicago All Star Jordan 5 Special Release !!',
      description: '1 of 1 ! !',
      alttext: 'Never worn!',
    },
  ],
  categories: [
    {
      id: 1,
      name: 'Sports',
      description: 'Rare sports memorabilia!',
    },
    {
      id: 1,
      name: 'Shoes',
      description: 'Exclusive Shoes',
    },
  ],
  itemscategories: [
    {
      itemId: 1,
      categoryId: 1,
    },
    {
      itemId: 2,
      categoryId: 2,
    },
    {
      itemId: 3,
      categoryId: 1,
  discounts: [
    {
      name: 'newuser',
      type: 'fixed',
      description: 'Introductory offer to new users',
      amount: 1000,
    },
    {
      name: 'tistheseason',
      type: 'fixed',
      description: 'seasonal discount',
      amount: 2000,
    },
  ],
  orders: [
    {
      userId: 1,
      total: 5243,
      complete: true,
      street: '777 Jackpot Avenue',
      apartment: '11',
      city: 'Atlantic City',
      state: 'New Jersey',
      zipcode: '08201',
      nameoncard: 'Berry Johnson',
      billingaddress: '777 Jackpot Avenue, 11, Atlantic City, NJ 08201',
      ccnumber: 123456789,
      ccsecuritycode: 555,
      ccexpiration: '10/25',
      cczipcode: '08201',
    },
    {
      userId: 2,
      total: 10253,
      complete: true,
      street: '123 Main Street',
      city: 'Wisconsin Dells',
      state: 'Wisconsin',
      zipcode: '53965',
      nameoncard: 'Joey Gouda',
      billingaddress: '123 Main Street, Wisconsin Dells, WI 53965',
      ccnumber: 123456789,
      ccsecuritycode: 345,
      ccexpiration: '1/24',
      cczipcode: '54965',
    },
    {
      userId: 1,
      total: 1233,
      complete: false,
      street: '777 Jackpot Avenue',
      apartment: '11',
      city: 'Atlantic City',
      state: 'New Jersey',
      zipcode: '08201',
      nameoncard: 'Berry Johnson',
      billingaddress: '777 Jackpot Avenue, 11, Atlantic City, NJ 08201',
      ccnumber: 123456789,
      ccsecuritycode: 555,
      ccexpiration: '10/25',
      cczipcode: '08201',
    },
  ],
  ordersitems: [
    {
      orderId: 1,
      itemId: 1,
      quantity: 5,
      priceatpurchase: 1100,
    },
    {
      orderId: 1,
      itemId: 2,
      quantity: 1,
      priceatpurchase: 556,
    },
    {
      orderId: 2,
      itemId: 2,
      quantity: 15,
      priceatpurchase: 542,
    },
    {
      orderId: 3,
      itemId: 2,
      quantity: 2,
      priceatpurchase: 600,
    },
    {
      orderId: 3,
      itemId: 1,
      quantity: 4,
      priceatpurchase: 340,
    },
  ],
  reviews: [
    {
      itemId: 1,
      userId: 1,
      title: 'What a jersey!',
      bodytext: 'You can still see all the mustard stains!',
    },
    {
      itemId: 2,
      userId: 2,
      title: 'Gorgeous shoes',
      bodytext: 'I still cant hit a jumper, but at least I look good.',
    },
  ],
};
