module.exports = {
  users: [
    {
      username: 'alabert',
      password: 'password',
      firstname: 'burton',
      lastname: 'guster',
      email: 'gus@psych.net',
      phonenumber: '555555555',
      zipcode: '93101',
    },
    {
      username: 'cat catsby',
      password: 'password',
      firstname: 'sydney',
      lastname: 'kitteh',
      email: 'grump@grump.net',
      phonenumber: '555555555',
      zipcode: '60615',
    },
  ],
  userpayments: [
    {
      userId: 1,
      cardname: 'visa debit card',
      nameoncard: 'Burton Guster',
      billingaddress: '123 Fake Street, Santa Barbara, California',
      ccnumber: 1234567891024,
      ccsecuritycode: 123,
      ccexpiration: '2/25',
      zipcode: '93101',
    },
    {
      userId: 1,
      cardname: 'home depot credit card',
      nameoncard: 'Burton Guster',
      billingaddress: '123 Fake Street, Santa Barbara, California',
      ccnumber: 564654156156,
      ccsecuritycode: 654,
      ccexpiration: '1/24',
      zipcode: '93101',
    },
  ],
  useraddresses: [
    {
      userId: 1,
      street: '123 Fake Street, Santa Barbara, California',
      city: 'Santa Barbara',
      state: 'California',
      zipcode: '93101',
    },
  ],
  orders: [
    {
      userId: 1,
      total: 5243,
      complete: true,
      street: '777 Jackpot Avenue',
      apartment: '11',
      city: 'Atlantic City',
      state: 'New Jersey',
      zipcode: '08201',
      nameoncard: 'Berry Johnson',
      billingaddress: '777 Jackpot Avenue, 11, Atlantic City, NJ 08201',
      ccnumber: 123456789,
      ccsecuritycode: 555,
      ccexpiration: '10/25',
      cczipcode: '08201',
    },
    {
      userId: 2,
      total: 10253,
      complete: true,
      street: '123 Main Street',
      city: 'Wisconsin Dells',
      state: 'Wisconsin',
      zipcode: '53965',
      nameoncard: 'Joey Gouda',
      billingaddress: '123 Main Street, Wisconsin Dells, WI 53965',
      ccnumber: 123456789,
      ccsecuritycode: 345,
      ccexpiration: '1/24',
      cczipcode: '54965',
    },
  ],
  ordersitems: [
    {
      orderId: 1,
      itemId: 1,
      quantity: 5,
      priceatpurchase: 1100,
    },
    {
      orderId: 1,
      itemId: 2,
      quantity: 1,
      priceatpurchase: 556,
    },
    {
      orderId: 2,
      itemId: 2,
      quantity: 15,
      priceatpurchase: 542,
    },
  ],
};
